<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<?xml-stylesheet type="text/xsl" href="Employees.xsl"?>

<!DOCTYPE employees [
   <!ELEMENT employees (employee)+>
   <!ELEMENT employee (employeeno, employeename, deptname, salary, yearofjoin)>
   <!ELEMENT employeeno (#PCDATA)>
   <!ELEMENT employeename (#PCDATA)>
   <!ELEMENT deptname (#PCDATA)>
   <!ELEMENT salary (#PCDATA)>
   <!ELEMENT yearofjoin (#PCDATA)>
]>

<employees>
  <employee>
    <employeeno>001</employeeno>
    <employeename>Nishant Nirmal</employeename>
    <deptname>IT</deptname>
    <salary>50000</salary>
    <yearofjoin>2020</yearofjoin>
  </employee>
</employees>